services:
  redis:
    image: redis:7.4.2
    ports:
      - "6378:6379"
    networks:
      - network

  mongodb:
    image: mongo:8.0.6
    ports:
      - "27018:27017"
    networks:
      - network

networks:
  network:
    driver: bridge
